apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ouaarpbzh-python
  janus-idp.io/tekton: ouaarpbzh-python
  backstage.io/kubernetes-id: ouaarpbzh-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ouaarpbzh-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
